doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'
        types:
            email: App\Core\Infrastructure\DoctrineTypes\EmailType
            pesel: App\Core\Infrastructure\DoctrineTypes\PeselType
            result_array: App\Core\Infrastructure\DoctrineTypes\TestResultArrayType
            indicators_array: App\Core\Infrastructure\DoctrineTypes\IndicatorsArrayType
        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '13'
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            Users:
                is_bundle: false
                type: xml
                dir: '%kernel.project_dir%/config/doctrine-mapping/Users'
                prefix: 'App\Users\Domain'
                alias: Users
            Laboratory:
                is_bundle: false
                type: xml
                dir: '%kernel.project_dir%/config/doctrine-mapping/Laboratory'
                prefix: 'App\Laboratory\Domain'
                alias: Laboratory
            MedicalTests:
                is_bundle: false
                type: xml
                dir: '%kernel.project_dir%/config/doctrine-mapping/MedicalTests'
                prefix: 'App\MedicalTests\Domain'
                alias: MedicalTests