security:
    providers:
        db_provider:
            id: App\Security\UserProvider
    password_hashers:
        App\Security\User: auto
        Symfony\Component\Security\Core\User\User: auto
    role_hierarchy:
        ROLE_SYSTEM_ADMIN: [ ROLE_LABORATORY_WORKER ]
        ROLE_LABORATORY_WORKER: [ ROLE_PATIENT ]
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            pattern: ^/
            anonymous: true
            logout:
                path: /logout
                target: /login-status
            json_login:
                check_path: /login

    access_control:
        - { path: ^/admin, roles: ROLE_SYSTEM_ADMIN }
        - { path: ^/lab-worker, roles: ROLE_LABORATORY_WORKER }
        - { path: ^/current-user, roles: ROLE_PATIENT }
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/, roles: ROLE_PATIENT }
