security:
    providers:
        db_provider:
            id: App\Security\UserProvider
    encoders:
        App\Security\User: auto
        Symfony\Component\Security\Core\User\User: auto
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            pattern: ^/
            anonymous: true
            logout:
                path: /logout
                target: /login-status
            json_login:
                check_path: /login

    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/, roles: ROLE_CLIENT_USER }
