parameters:
  senderEmail: '%env(resolve:SENDER_EMAIL)%'
services:
  # default configuration for services in *this* file
  _defaults:
    autowire: true      # Automatically injects dependencies in your services.
    autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
    bind:
      $senderEmail: '%senderEmail%'

  App\Core\Domain\Clock:
    class: App\Core\Domain\Clock\TestClock

  App\Mailer\Application\EmailSender:
    class: App\Mailer\Application\DummyEmailSender
    public: true
